#set up node enviro
language: node_js

#lts represents long-term support (stable release of node js)
node_js:
  - lts/*

#after node enviro:
#remove by force .git inside the CIT384_Final_Project/ repo
#compile my source code in ~/project ; build updated code
#clone .git folder of PUBLIC repo
#mv the .git that we cloned to dist folder (compiled code)
#cd dist
#rm old origin
#add to the origin in PUBLIC repo
#stage changs that will be made
#commit -m "message" [of stage changes]
#push to declared branch on travs CI
after_success:
  - rm -rf .git
  - npm run build
  - git clone https://github.com/JennyM0715/CIT384_Final_Project-PUBLIC.git
  - mv CIT384_Final_Project-PUBLIC/.git dist/
  - cd dist
  - git remote rm origin
  #- git remote add origin https://github.com/JennyM0715/CIT384_Final_Project-PUBLIC
  - git remote add origin https://username:${GH_TOKEN}@github.com/JennyM0715/CIT384_Final_Project-PUBLIC
  - git add .
  - git commit -m "Completed Travis-CI automated build"
  - git push -fq origin ${GIT_BRANCH}
